export const Button = {
  sizes: {
    md: {
      fontSize: '1rem',
      minH: '3rem',
      width: '15rem',
      p: '1rem 1.5rem',
      borderRadius: '2.5rem',
    },
    sm: {
      fontSize: '0.875rem',
      minH: '2.5rem',
      width: '12.5rem',
      p: '0.75rem 1.5rem',
      borderRadius: '2.5rem',
    },
    xs: {
      fontSize: '0.875rem',
      fontWeight: 'normal',
      letterSpacing: '0.1em',
      minH: '2.375rem',
      minWidth: '4rem',
      p: '0.75rem 1rem',
      borderRadius: '2rem',
    },
  },
  variants: {
    primary: {
      bg: 'blue.500',
      color: 'neutral.0',
      lineHeight: '100%',
      _hover: { bg: 'blue.600', _disabled: { bg: 'blue.500' } },
      _active: { bg: 'blue.700' },
      _disabled: { opacity: 0.5 },
      spinnerColor: 'neutral.0',
    },
    secondary: {
      bg: 'neutral.0',
      color: 'neutral.800',
      lineHeight: '100%',
      border: '1px solid',
      borderColor: 'blue.500',
      _hover: { bg: 'blue.100', _disabled: { bg: 'neutral.0' } },
      _active: { bg: 'blue.200' },
      _disabled: { opacity: 0.5 },
    },
    negative: {
      bg: 'neutral.300',
      color: 'neutral.800',
      lineHeight: '100%',
      _hover: { bg: 'neutral.400', _disabled: { bg: 'neutral.300' } },
      _active: { bg: 'neutral.500' },
      _disabled: { bg: 'neutral.300', opacity: 0.5 },
    },
    danger: {
      bg: 'neutral.0',
      color: 'danger.700',
      lineHeight: '100%',
      border: '2px solid',
      borderColor: 'danger.700',
      _hover: { bg: 'danger.100', _disabled: { bg: 'neutral.0' } },
      _active: { bg: 'danger.200' },
      _disabled: { opacity: 0.5 },
    },
  },
  defaultProps: {
    size: 'md',
    variant: 'primary',
  },
}
